[tasks.graphs]
help = "Run all graph scripts (Vue, Django)"
args = [{ name = "OPTION", positional = true, multiple = true }]
sequence = [
  "comps_graph ${OPTION}",
  "models_graph ${OPTION}",
]

[tasks.comps_graph]
help = "Create Vue components graph"
args = [{ name = "OPTION", help="None to update file, else `show` or `dot`", required=false, positional=true, default="None" }]
shell = """
mkdir -p docs
cmd="dot -Tpng -odocs/comps_graph.png"
if [ ${OPTION} = "show" ]; then
  cmd="dot -Tx11"
elif [ ${OPTION} = "dot" ]; then
  cmd="cat"
fi
(
  echo "digraph {"
  for v in $(find front/src -name '*.vue'); do
    c=$(basename $v .vue)
    sed -rn "/components: \\{/,/\\}/{/[{}]/d;s/[ ,]+//g;p}" "$v" | xargs -i@ echo "$c -> @"
  done
  echo "}"
) | $cmd
"""

[tasks.models_graph]
help = "Create django model graph"
args = [{ name = "OPTION", help="None to update file, else `show` or `dot`", required=false, positional=true, default="None" }]
shell = """
mkdir -p docs
cmd="dot -Tpng -odocs/models_graph.png"
if [ ${OPTION} = "show" ]; then
  cmd="dot -Tx11"
elif [ ${OPTION} = "dot" ]; then
  cmd="cat"
fi
./back/manage.py graph_models myapp | $cmd
"""
