[tasks.graphs]
help = "Run all graph scripts (React, Django)"
args = [{ name = "OPTION", positional = true, multiple = true }]
sequence = [
  "comps_graph ${OPTION}",
  "models_graph ${OPTION}",
]

[tasks.comps_graph]
help = "Create React components graph"
args = [{ name = "OPTION", help="None to update file, else `show` or `dot`", required=false, positional=true, default="None" }]
cmd = "./front/.scripts/comps_graph"

[tasks.models_graph]
help = "Create django model graph"
args = [{ name = "OPTION", help="None to update file, else `show` or `dot`", required=false, positional=true, default="None" }]
shell = """
mkdir -p docs
cmd="dot -Tpng -odocs/models_graph.png"
if [ ${OPTION} = "show" ]; then
  cmd="dot -Tx11"
elif [ ${OPTION} = "dot" ]; then
  cmd="cat"
fi
./back/manage.py graph_models myapp | $cmd
"""
