[tasks.secret_tests]
help = "Analyse secret"
shell = """
set -e
HERE="$(git rev-parse --show-toplevel)"
exec docker run --rm -v "$HERE:/app" -w /app registry.gitlab.com/systracorp/hq/infra/git-secret-analyzer:1.2.0
"""
