[tasks.secret_tests]
help = "Analyse secret"
shell = """
set -e
HERE="$(git rev-parse --show-toplevel)"
exec docker run --rm -v "$HERE:/app" -w /app zricethezav/gitleaks:v8.30.0 git /app --log-opts HEAD -v
"""
