include:
  - component: $CI_SERVER_FQDN/systracorp/hq/infra/ci/security@0.8
  - component: $CI_SERVER_FQDN/systracorp/hq/infra/ci/python-linter@0.8
  - component: $CI_SERVER_FQDN/systracorp/hq/infra/ci/python-i18n@0.8
    inputs:
      system-packages: 'gettext git'
  - component: $CI_SERVER_FQDN/systracorp/hq/infra/ci/python-tests@0.8
    inputs:
      system-packages: 'postgresql-client'
      future-system-packages: 'postgresql-client'
      future-enable: true
  - component: $CI_SERVER_FQDN/systracorp/hq/infra/ci/js-linter@0.8
  - component: $CI_SERVER_FQDN/systracorp/hq/infra/ci/js-i18n@0.8
  - component: $CI_SERVER_FQDN/systracorp/hq/infra/ci/js-tests@0.8
    inputs:
      future-enable: true
  - component: $CI_SERVER_FQDN/systracorp/hq/infra/ci/total-coverage@0.8
  - component: $CI_SERVER_FQDN/systracorp/hq/infra/ci/docker-test@0.8
  - component: $CI_SERVER_FQDN/systracorp/hq/infra/ci/tag@0.8
    inputs:
      needs:
        - security
        - secret
        - python-linter
        - python-i18n
        - python-tests
        - js-linter
        - js-i18n
        - js-tests
        - docker-test
  - component: $CI_SERVER_FQDN/systracorp/hq/infra/ci/docker-publish@0.8
  - component: $CI_SERVER_FQDN/systracorp/hq/infra/ci/release@0.8
    inputs:
      needs:
        - docker-publish

# extra parameters to use a postgresql service
python-tests: &python-pg-svc
  services:
    - name: postgres:17-alpine
      alias: db
      variables:
        POSTGRES_DB: "${CI_PROJECT_NAME}"
        POSTGRES_USER: "${CI_PROJECT_NAME}"
        POSTGRES_PASSWORD: "${CI_PROJECT_NAME}"
        POSTGRES_HOST_AUTH_METHOD: trust
  variables:
    DJANGO_DB_TYPE: postgresql
    DB_HOST: db
python-tests:future:
  <<: *python-pg-svc
