# vim: set st=2 sts=2 sw=2 et:
---
name: myapp
services:
  db:
    image: postgres:18-alpine
    healthcheck:
      test: ["CMD", "/docker-healthcheck"]
      interval: 30s
      timeout: 2s
      retries: 20
    environment:
      - POSTGRES_DB=myapp
      - POSTGRES_USER=myapp
      - POSTGRES_PASSWORD=myapp
    volumes:
      - type: volume
        source: db
        target: /var/lib/postgresql/18/docker
        read_only: false
      - type: bind
        source: ./docker/dev/db-healthcheck
        target: /docker-healthcheck
        read_only: true
  app:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
      secrets:
        - GITLAB_TOKEN
    depends_on:
      db:
        condition: service_healthy
    environment:
      - "UV_LINK_MODE=copy"
      - "PRE_EP_PATH=/preentrypoint.sh"
      - "PRE_START_PATH=/prestart.sh"
      - "DJANGO_DB_TYPE=postgresql"
      - "DJANGO_DB_HOST=db"
      - "DJANGO_DB_PORT=5432"
      - "DJANGO_VITE_DEV_MODE=1"
      - "DJANGO_PORT=${DJANGO_PORT:-8000}"
      - "PORT=${PORT:-3978}"
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - type: bind
        source: .
        target: /app
        read_only: false
        bind:
          create_host_path: false
      - type: bind
        source: ./docker/dev/preentrypoint.sh
        target: /preentrypoint.sh
        read_only: true
      - type: bind
        source: ./docker/dev/prestart.sh
        target: /prestart.sh
        read_only: true
      - type: bind
        source: ./docker/dev/django-command
        target: /django-command
        read_only: true
      - type: bind
        source: ./docker/dev/django.conf
        target: /etc/supervisor/conf.d/django.conf
        read_only: true
      - type: bind
        source: ./docker/dev/tasks-command
        target: /tasks-command
        read_only: true
      - type: bind
        source: ./docker/dev/tasks.conf
        target: /etc/supervisor/conf.d/tasks.conf
        read_only: true
      - type: bind
        source: ./docker/dev/vite-command
        target: /vite-command
        read_only: true
      - type: bind
        source: ./docker/dev/vite.conf
        target: /etc/supervisor/conf.d/vite.conf
        read_only: true
    ports:
      - ${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}
      - ${PORT:-3978}:${PORT:-3978}
volumes:
  db:
secrets:
  GITLAB_TOKEN:
    environment: "GITLAB_TOKEN"
