#!/bin/sh
set -e
cd "$(dirname "$0")"
if [ -z "$1" ]; then
  echo "You must specify the new application name as first argument" >&2
  exit 1
elif ! echo "$1" | grep -Eq '^[a-z_]+$'; then
  echo "The new application name should be lower case only + underscore" >&2
  exit 1
fi
name="$1"
if [ -n "$2" ] && echo "$2" | grep -Eq '^https?:'; then
  url="$2"
else
  echo "You must specify the new application url as second argument" >&2
  exit 1
fi
# shellcheck disable=SC2018,SC2019
uname="$(echo "$name"|tr '_' ' '|sed -E 's/(^| )([a-z])/\1\u\2/g')"
for f in \
  README.md \
  pyproject.toml \
  package.json \
  $(find docker -type f) \
  back/myapp/templates/index.html \
  .gitlab/merge_request_templates/code-review-checklist.md \
  .gitlab-ci.yml \
  .gitignore \
  .gitleaks.toml \
  .dockerignore \
  .prod-docker-compose.yml \
  $(find .poe -type f) \
  $(find . -type f \( -name '*.*js' -o -name '*.[jt]sx' \)) \
  $(find . -type f -name '*.py') \
  $(find . -type f -name '*.po') \
  $(find . -type f \( -name '*.yml' -o -name '*.lock' \)) \
; do
  sed -Ei -e "s/myapp/$name/g" -e "s/Myapp/$uname/g" "$f"
done
mv back/myapp back/"$name"
# set version to 0.1.0
sed -Ei '/^version =/{s/".*"/"0.1.0"/}' pyproject.toml
sed -Ei '/^  "version": /{s/".*"/"version": "0.1.0"/}' package.json
sed -Ei "/Code Generators/d" pyproject.toml
sed -Ei "/Start of Boilerplate doc/,/End of Boilerplate doc/d" README.md
if [ -n "$url" ]; then
  base_url=$(dirname "$url")
  for f in \
    README.md \
    pyproject.toml \
    package.json \
    .gitlab/merge_request_templates/code-review-checklist.md \
  ; do
    sed -Ei "s|https://gitlab.com/.*/boilerplates/[-a-z0-9]+|$url|" "$f"
    sed -Ei "s|https://gitlab.com/.*/boilerplates|$base_url|" "$f"
  done
fi
rm -rf CHANGELOG.md exit .git
cat <<EOF
Don’t forget to:
- edit the LICENSE file
- edit pyproject.toml file (description, author, private, urls)
- edit package.json file (description, author, private, urls)
- edit README.md file (badges, description, env variables)
- change the static assets files
- change the favicon.ico icon file
EOF
