# Generated by Django 4.2.7 on 2023-11-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_category_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, max_length=1023, null=True, upload_to=""
            ),
        ),
    ]
