[program:worker]
command=env -C /var/www/climateplus uv run poe tasks worker
startretries=10
autorestart=true
stopwaitsecs=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scheduler]
command=env -C /var/www/climateplus uv run poe tasks scheduler
startretries=10
autorestart=true
stopwaitsecs=3
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
