#!/bin/sh
mkdir -p docs
cmd="dot -Tpng -odocs/comps_graph.png"
if [ "${OPTION}" = "show" ]; then
  cmd="dot -Tx11"
elif [ "${OPTION}" = "dot" ]; then
  cmd="cat"
fi
(
  echo "digraph {"
  for v in $(find front/src \( -name '*.js*' -a \! -name '*.json' \)); do
    c=$(basename $v|sed -E 's/\..+$//')
    sed -En '/from '"'"'(@src|@page|@comp|@scss|\.\/)[^.]+(.[jt]sx?)?'"'"'/{s|.*'"'"'.+/([^.]+)(\..+)?'"'"'.*|\1|;p}' "$v" | xargs -i@ echo "\"$c\" -> \"@\""
  done
  echo "}"
) | $cmd

