#!/bin/sh
POT_FILE="front/src/locale/messages.pot"
$(dirname "$0")/gettext-extract >/dev/null
DEFAULT_LANG=$(jq -r '.default' front/locales.json)
AVAILABLE_LANGS=$(jq -r '.languages|keys[]' front/locales.json | grep -v "^$DEFAULT_LANG")
echo '__________________________________________________'
msg_ko=
for lang in $AVAILABLE_LANGS; do
  PO_FILE="front/src/locale/$lang.po"
  if [ -f "$PO_FILE" ]; then
    echo "Analyzing $PO_FILE"
    untranslated=$(msgattrib --no-wrap -F --untranslated "$PO_FILE")
    if [ -n "$untranslated" ]; then
      echo "$untranslated" >&2
      msg_ko=1
    fi
  fi
done
if [ -z "$msg_ko" ]; then
  echo "Ok"
else
  exit 1
fi
