#!/bin/sh
LOCALE_DIR=./front/src/i18n/locales
POT_FILE="$LOCALE_DIR/messages.pot"
# force to update POT/PO files
$(dirname "$0")/gettext-extract >/dev/null
# define DEFAULT_LANG and AVAILABLE_LANGS env vars
eval $(
  node -e "const locales = require('./front/src/i18n/locales.json'); console.log('DEFAULT_LANG=' + locales.default); console.log('AVAILABLE_LANGS=\"' + Object.keys(locales.languages).join(' ') + '\"')"
)
echo '__________________________________________________'
msg_ko=
for lang in $AVAILABLE_LANGS; do
  PO_FILE="$LOCALE_DIR/$lang.po"
  if [ -f "$PO_FILE" ]; then
    echo "Analyzing $PO_FILE"
    untranslated=$(msgattrib --no-wrap -F --untranslated "$PO_FILE")
    if [ -n "$untranslated" ]; then
      echo "$untranslated" >&2
      msg_ko=1
    fi
  fi
done
if [ -z "$msg_ko" ]; then
  echo "Ok"
else
  exit 1
fi
